import type { NextPage } from 'next'
import Head from 'next/head'
import { Container } from '@chakra-ui/react'

import Header from '../components/Header'
import About from '../views/About'
import Banner from '../views/Banner'
import Contacts from '../views/Contacts'
import Projects from '../views/Projects'
import Skills from '../views/Skills'

const Home: NextPage = () => {
  return (
    <div>
      <Head>
        <title>Create Next App</title>
        <meta name="description" content="Generated by create next app" />
        <link rel="icon" href="/favicon.ico" />
      </Head>

      <div className="App">
        <Header />
        <main>
          <Banner />
          <Container maxW="container.lg" id="wrapper">
            <About />
          </Container>
          <Container maxW="container.xl" id="wrapper">
            <Skills />
            <Projects />
            <Contacts />
          </Container>
        </main>
      </div>
    </div>
  )
}

export default Home
